{% set name = "bayesianbandits" %}
{% set version = "0.8.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/bayesianbandits-{{ version }}.tar.gz
  sha256: f19a9a1f8d98bcdbf7568034e0fcbd881be0647633a364f09da9103402f2d1af

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9,<3.13
    - poetry-core
    - pip
  run:
    - python >=3.9.0,<4.0.0,<3.13
    - scipy >=1.11.0
    - scikit-learn >=1.2.0
    - attrs >=21.2.0
    - typing-extensions >=4.8.0

test:
  imports:
    - bayesianbandits
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/bayesianbandits/bayesianbandits
  doc_url: https://bayesianbandits.readthedocs.io/en/latest/
  summary: A Pythonic microframework for Multi-Armed Bandit algorithms.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
