{% set name = "bayesianbandits" %}
{% set version = "1.1.0" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/bayesianbandits-{{ version }}.tar.gz
  sha256: db33d4ef3247fdda7658f76198b154ddc3c20892d395807715d962104970c13f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }}
    - scipy >=1.14.0
    - scikit-learn >=1.3.0
    - numpy >=1.23.5
    - typing_extensions >=4.8.0
    - attrs >=21.2.0

test:
  imports:
    - bayesianbandits
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/bayesianbandits/bayesianbandits
  doc_url: https://bayesianbandits.readthedocs.io/en/latest/
  summary: A Pythonic microframework for Multi-Armed Bandit algorithms.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
