{% set name = "bayesianbandits" %}
{% set version = "0.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/bayesianbandits-{{ version }}.tar.gz
  sha256: 515256598f86dbec0f67b593599e5a9d2bb1132e85ca731b541d75cc35ded33c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9,<3.13
    - poetry-core
    - pip
  run:
    - python >=3.9.0,<4.0.0,<3.13
    - scipy >=1.11.0
    - scikit-learn >=1.2.0
    - attrs >=21.2.0
    - typing-extensions >=4.8.0

test:
  imports:
    - bayesianbandits
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/bayesianbandits/bayesianbandits
  doc_url: https://bayesianbandits.readthedocs.io/en/latest/
  summary: A Pythonic microframework for Multi-Armed Bandit algorithms.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
